[workspace]
authors = ["Nickolas K Freeman <nick.freeman524@gmail.com>"]
channels = ["conda-forge"]
name = "reddit"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
polars = ">=1.44.2,<2"
pyarrow = ">=25.0.0,<26"
numpy = ">=2.5.3,<3"
scipy = ">=1.18.1,<2"
statsmodels = ">=0.15.0,<0.16"
matplotlib = ">=3.11.2,<4"
seaborn = ">=0.13.2,<0.14"
requests = ">=2.34.2,<3"
jinja2 = ">=3.1.6,<4"
pytest = ">=9.1.1,<10"
