"""Generate paper figures and LaTeX values from derived summaries."""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path

import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import numpy as np
import polars as pl
import seaborn as sns


DERIVED = Path("derived")
PAPER = Path("paper")
FIGURES = PAPER / "figures"
ANALYSIS_END = date(2026, 9, 19)


def put_macro(name: str, value: str) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}\n"


def build_variables(summary: dict, daily: pl.DataFrame) -> None:
    clean = daily.filter(pl.col("date") <= ANALYSIS_END)
    recent = clean.filter(pl.col("date") >= date(2025, 1, 1))
    first_2025 = recent.filter(pl.col("date").dt.year() == 2025)
    current_2026 = recent.filter(pl.col("date").dt.year() == 2026)
    macros = [
        "% Auto-generated by generate_outputs.py. Do not edit.\n",
        "% Regenerate: MPLBACKEND=Agg pixi run python generate_outputs.py\n",
        put_macro("dataUserDays", f"{summary['analyzed_rows']:,}"),
        put_macro("dataPosts", f"{summary['total_posts']:,}"),
        put_macro("dataAccounts", f"{summary['account_count']:,}"),
        put_macro("dataFirstDate", summary["first_date"]),
        put_macro("dataLastRawDate", summary["last_date"]),
        put_macro("dataAnalysisEnd", str(ANALYSIS_END)),
        put_macro("dataObservedDates", f"{summary['observed_dates']:,}"),
        put_macro("dataCalendarDays", f"{summary['calendar_days']:,}"),
        put_macro("dataMissingDates", f"{summary['calendar_days'] - summary['observed_dates']:,}"),
        put_macro("dataRecentDates", f"{recent.height:,}"),
        put_macro("dataSingleDayAccounts", f"{summary['single_day_accounts']:,}"),
        put_macro("dataTopShare", f"{100 * summary['top_point_one_percent_post_share']:.1f}\\%"),
        put_macro("dataTopAccounts", f"{summary['top_point_one_percent_accounts']:,}"),
        put_macro("dataMaxDaily", f"{summary['account_max_daily_posts']:,}"),
        put_macro("dataMedianAccountPosts", f"{summary['account_total_median']:.0f}"),
        put_macro("dataPnnAccountPosts", f"{summary['account_total_p99']:.0f}"),
        put_macro("dataHighUserDays", f"{summary['user_day_count_ge_20']:,}"),
        put_macro("dataTwentyFiveMean", f"{first_2025['posts'].mean():,.0f}"),
        put_macro("dataTwentySixMean", f"{current_2026['posts'].mean():,.0f}"),
        put_macro("dataLastDayPosts", f"{daily.tail(1)['posts'].item():,}"),
        put_macro("dataLastStablePosts", f"{clean.tail(1)['posts'].item():,}"),
    ]
    for event in summary["events"]:
        if event["status"] != "estimated":
            continue
        prefix = "claude" if event["event"].startswith("Claude") else "codex"
        if event.get("outcome") == "posts_excluding_20_plus_days":
            macros.append(put_macro(prefix + "Sensitivity", f"{event['level_change_pct']:.2f}"))
            continue
        for suffix, key in [
            ("Change", "level_change_pct"),
            ("Low", "level_change_ci_low_pct"),
            ("High", "level_change_ci_high_pct"),
            ("P", "holm_p"),
        ]:
            macros.append(put_macro(prefix + suffix, f"{event[key]:.2f}" if suffix != "P" else f"{event[key]:.3f}"))
    (PAPER / "variables.tex").write_text("".join(macros))


def build_figures(daily: pl.DataFrame) -> None:
    sns.set_style("whitegrid")
    plt.rcParams.update({"font.family": "serif", "font.serif": ["Nimbus Roman", "Times New Roman", "DejaVu Serif"], "font.size": 10})
    clean = daily.filter(pl.col("date") <= ANALYSIS_END)
    monthly = (
        clean.filter(pl.col("date") < date(2026, 9, 1))
        .with_columns(pl.col("date").dt.truncate("1mo").alias("month"))
        .group_by("month")
        .agg(pl.sum("posts").alias("posts"))
        .sort("month")
    )
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(monthly["month"].to_list(), monthly["posts"].to_numpy() / 1e6, color="#21618c", linewidth=1.7)
    ax.set_ylabel("Posts per month (millions)")
    ax.set_xlabel("Month")
    ax.set_ylim(bottom=0)
    ax.xaxis.set_major_locator(mdates.YearLocator(2))
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y"))
    sns.despine(ax=ax)
    fig.tight_layout()
    fig.savefig(FIGURES / "monthly_volume.pdf")
    fig.savefig(FIGURES / "monthly_volume.png", dpi=200)
    plt.close(fig)

    recent = clean.filter(pl.col("date") >= date(2025, 1, 1))
    dates = recent["date"].to_list()
    posts = recent["posts"].to_numpy().astype(float)
    users = recent["active_users"].to_numpy().astype(float)
    def trailing_mean(values: np.ndarray) -> np.ndarray:
        return np.array([values[max(0, index - 6): index + 1].mean() for index in range(len(values))])
    fig, axes = plt.subplots(nrows=2, ncols=1, figsize=(8, 6.5), sharex=True)
    axes[0].plot(dates, trailing_mean(posts) / 1e3, color="#21618c", linewidth=1.6)
    axes[1].plot(dates, trailing_mean(users) / 1e3, color="#1b9e77", linewidth=1.6)
    for ax in axes:
        ax.axvline(date(2025, 2, 24), color="#a0522d", linestyle="--", linewidth=1, label="Claude Code preview")
        ax.axvline(date(2025, 5, 16), color="#7b3294", linestyle=":", linewidth=1.5, label="Codex preview")
        sns.despine(ax=ax)
    axes[0].set_ylabel("Daily posts (thousands)")
    axes[1].set_ylabel("Active users (thousands)")
    axes[1].set_xlabel("Date")
    axes[0].legend(loc="upper right", frameon=False, fontsize=8)
    axes[1].xaxis.set_major_locator(mdates.MonthLocator(interval=3))
    axes[1].xaxis.set_major_formatter(mdates.DateFormatter("%b %Y"))
    fig.autofmt_xdate(rotation=0)
    fig.tight_layout()
    fig.savefig(FIGURES / "recent_activity.pdf")
    fig.savefig(FIGURES / "recent_activity.png", dpi=200)
    plt.close(fig)


def main() -> None:
    summary = json.loads((DERIVED / "summary.json").read_text())
    daily = pl.read_parquet(DERIVED / "daily_summary.parquet")
    assert daily["posts"].sum() == summary["total_posts"]
    assert date.fromisoformat(summary["last_date"]) >= ANALYSIS_END
    PAPER.mkdir(exist_ok=True)
    FIGURES.mkdir(exist_ok=True)
    build_variables(summary, daily)
    build_figures(daily)
    print("Generated variables and two figures through", ANALYSIS_END)


if __name__ == "__main__":
    main()
