"""Generate paper figures and LaTeX values from derived summaries."""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path

import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import numpy as np
import polars as pl
import seaborn as sns


DERIVED = Path("derived")
PAPER = Path("paper")
FIGURES = PAPER / "figures"
ANALYSIS_END = date(2026, 9, 19)


def put_macro(name: str, value: str) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}\n"


def build_variables(summary: dict, daily: pl.DataFrame) -> None:
    clean = daily.filter(pl.col("date") <= ANALYSIS_END)
    recent = clean.filter(pl.col("date") >= date(2025, 1, 1))
    first_2025 = recent.filter(pl.col("date").dt.year() == 2025)
    current_2026 = recent.filter(pl.col("date").dt.year() == 2026)
    october_2024 = clean.filter(
        (pl.col("date") >= date(2024, 10, 1))
        & (pl.col("date") < date(2024, 11, 1))
    )
    january_2025 = clean.filter(
        (pl.col("date") >= date(2025, 1, 1))
        & (pl.col("date") < date(2025, 2, 1))
    )
    macros = [
        "% Auto-generated by generate_outputs.py. Do not edit.\n",
        "% Regenerate: MPLBACKEND=Agg pixi run python generate_outputs.py\n",
        put_macro("dataUserDays", f"{summary['analyzed_rows']:,}"),
        put_macro("dataPosts", f"{summary['total_posts']:,}"),
        put_macro("dataAccounts", f"{summary['account_count']:,}"),
        put_macro("dataFirstDate", summary["first_date"]),
        put_macro("dataLastRawDate", summary["last_date"]),
        put_macro("dataAnalysisEnd", str(ANALYSIS_END)),
        put_macro("dataObservedDates", f"{summary['observed_dates']:,}"),
        put_macro("dataCalendarDays", f"{summary['calendar_days']:,}"),
        put_macro("dataMissingDates", f"{summary['calendar_days'] - summary['observed_dates']:,}"),
        put_macro("dataRecentDates", f"{recent.height:,}"),
        put_macro("dataSingleDayAccounts", f"{summary['single_day_accounts']:,}"),
        put_macro("dataTopShare", f"{100 * summary['top_point_one_percent_post_share']:.1f}\\%"),
        put_macro("dataTopAccounts", f"{summary['top_point_one_percent_accounts']:,}"),
        put_macro("dataMaxDaily", f"{summary['account_max_daily_posts']:,}"),
        put_macro("dataMedianAccountPosts", f"{summary['account_total_median']:.0f}"),
        put_macro("dataPnnAccountPosts", f"{summary['account_total_p99']:.0f}"),
        put_macro("dataHighUserDays", f"{summary['user_day_count_ge_20']:,}"),
        put_macro("dataTwentyFiveMean", f"{first_2025['posts'].mean():,.0f}"),
        put_macro("dataTwentySixMean", f"{current_2026['posts'].mean():,.0f}"),
        put_macro("dataOctoberTwentyFourMean", f"{october_2024['posts'].mean():,.0f}"),
        put_macro("dataJanuaryTwentyFiveMean", f"{january_2025['posts'].mean():,.0f}"),
        put_macro("dataLastDayPosts", f"{daily.tail(1)['posts'].item():,}"),
        put_macro("dataLastStablePosts", f"{clean.tail(1)['posts'].item():,}"),
    ]
    for event in summary["events"]:
        if event["status"] != "estimated" or event["window_days"] != 30:
            continue
        prefix = "claude" if event["event"].startswith("Claude") else "codex"
        if event["trend"] == "quadratic":
            macros.append(put_macro(prefix + "Quadratic", f"{event['level_change_pct']:.2f}"))
            macros.append(put_macro(prefix + "QuadraticLow", f"{event['level_change_ci_low_pct']:.2f}"))
            macros.append(put_macro(prefix + "QuadraticHigh", f"{event['level_change_ci_high_pct']:.2f}"))
            continue
        if event.get("outcome") == "posts_excluding_20_plus_days":
            macros.append(put_macro(prefix + "Sensitivity", f"{event['level_change_pct']:.2f}"))
            continue
        macros.append(put_macro(prefix + "RemovedShare", f"{100 * event['removed_post_share']:.1f}\\%"))
        for suffix, key in [
            ("Change", "level_change_pct"),
            ("Low", "level_change_ci_low_pct"),
            ("High", "level_change_ci_high_pct"),
            ("P", "holm_p"),
        ]:
            macros.append(put_macro(prefix + suffix, f"{event[key]:.2f}" if suffix != "P" else f"{event[key]:.3f}"))
    (PAPER / "variables.tex").write_text("".join(macros))
    windows = [14, 21, 30, 45, 60]
    lines = [
        "\\begin{tabular}{rcc}\n",
        "\\toprule\n",
        "Days on each side & Claude Code (\\%) & Codex (\\%) \\\\\n",
        "\\midrule\n",
    ]
    for window in windows:
        cells = []
        for label in ["Claude Code", "Codex"]:
            event = next(
                item
                for item in summary["events"]
                if item["event"].startswith(label)
                and item.get("window_days") == window
                and item.get("outcome") == "posts"
                and item.get("trend") == "linear"
            )
            cells.append(
                f"{event['level_change_pct']:+.2f} "
                f"[{event['level_change_ci_low_pct']:+.2f}, "
                f"{event['level_change_ci_high_pct']:+.2f}]"
            )
        lines.append(f"{window} & {cells[0]} & {cells[1]} \\\\\n")
    lines.extend(["\\bottomrule\n", "\\end{tabular}\n"])
    (PAPER / "window_table.tex").write_text("".join(lines))


def build_figures(daily: pl.DataFrame) -> None:
    sns.set_style("whitegrid")
    plt.rcParams.update(
        {
            "font.family": "serif",
            "font.serif": ["Nimbus Roman", "Times New Roman", "DejaVu Serif"],
            "font.size": 10,
        }
    )
    clean = daily.filter(pl.col("date") <= ANALYSIS_END)
    monthly_observed = (
        clean.filter(pl.col("date") < date(2026, 9, 1))
        .with_columns(pl.col("date").dt.truncate("1mo").alias("month"))
        .group_by("month")
        .agg(pl.sum("posts").alias("posts"))
        .sort("month")
    )
    months = pl.DataFrame(
        {
            "month": pl.date_range(
                start=date(2006, 4, 1),
                end=date(2026, 8, 1),
                interval="1mo",
                eager=True,
            )
        }
    )
    monthly = months.join(monthly_observed, on="month", how="left")
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(
        monthly["month"].to_list(),
        monthly["posts"].to_numpy() / 1e6,
        color="#21618c",
    )
    ax.set_ylabel("Posts per month (millions)")
    ax.set_xlabel("Month")
    ax.set_ylim(bottom=0)
    ax.xaxis.set_major_locator(mdates.YearLocator(2))
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%Y"))
    sns.despine(ax=ax)
    fig.tight_layout()
    fig.savefig(FIGURES / "monthly_volume.pdf")
    fig.savefig(FIGURES / "monthly_volume.png", dpi=200)
    plt.close(fig)

    recent = clean.filter(pl.col("date") >= date(2025, 1, 1))
    dates = recent["date"].to_list()
    posts = recent["posts"].to_numpy().astype(float)
    users = recent["active_users"].to_numpy().astype(float)
    def trailing_mean(values: np.ndarray) -> np.ndarray:
        return np.array([values[max(0, index - 6): index + 1].mean() for index in range(len(values))])
    fig, axes = plt.subplots(
        nrows=2,
        ncols=1,
        figsize=(8, 6.5),
        sharex=True,
    )
    axes[0].plot(dates, trailing_mean(posts) / 1e3, color="#21618c")
    axes[1].plot(dates, trailing_mean(users) / 1e3, color="#1b9e77")
    for ax in axes:
        ax.axvline(
            x=date(2025, 2, 24),
            color="#a0522d",
            linestyle="--",
            linewidth=1,
            label="Claude Code preview",
        )
        ax.axvline(
            x=date(2025, 5, 16),
            color="#7b3294",
            linestyle=":",
            linewidth=1.5,
            label="Codex preview",
        )
        sns.despine(ax=ax)
    axes[0].set_ylabel("Daily posts (thousands)")
    axes[1].set_ylabel("Active identifiers (thousands)")
    axes[1].set_xlabel("Date")
    axes[0].legend(
        loc="upper right",
        frameon=False,
        fontsize=8,
    )
    axes[1].xaxis.set_major_locator(mdates.MonthLocator(interval=3))
    axes[1].xaxis.set_major_formatter(mdates.DateFormatter("%b %Y"))
    axes[1].set_xlim(date(2025, 1, 1), ANALYSIS_END)
    fig.autofmt_xdate(rotation=0)
    fig.tight_layout()
    fig.savefig(FIGURES / "recent_activity.pdf")
    fig.savefig(FIGURES / "recent_activity.png", dpi=200)
    plt.close(fig)


def build_event_figure(summary: dict) -> None:
    sns.set_style("whitegrid")
    plt.rcParams.update(
        {
            "font.family": "serif",
            "font.serif": ["Nimbus Roman", "Times New Roman", "DejaVu Serif"],
            "font.size": 10,
        }
    )
    fig, axes = plt.subplots(
        nrows=2,
        ncols=1,
        figsize=(8, 5.5),
        sharey=True,
        sharex=True,
    )
    for axis, label in zip(axes, ["Claude Code", "Codex"]):
        event = next(
            item
            for item in summary["events"]
            if item["event"].startswith(label)
            and item.get("window_days") == 30
            and item.get("outcome") == "posts"
            and item.get("trend") == "linear"
        )
        offsets = np.array(event["offsets"])
        observed = np.array(event["observed_posts"]) / 1000
        fitted = np.array(event["fitted_trend_posts"]) / 1000
        axis.scatter(
            x=offsets,
            y=observed,
            color="#21618c",
            edgecolor="k",
            linewidth=0.25,
            alpha=0.65,
            s=16,
            label="Observed",
        )
        axis.plot(offsets[:30], fitted[:30], color="#a0522d")
        axis.plot(offsets[30:], fitted[30:], color="#a0522d", label="Fitted")
        axis.axvline(x=0, color="0.35", linestyle="--", linewidth=1)
        axis.set_title(label)
        axis.set_xlim(-31, 31)
        sns.despine(ax=axis)
    axes[0].set_ylabel("Daily posts (thousands)")
    axes[1].set_ylabel("Daily posts (thousands)")
    axes[1].set_xlabel("Days from announcement")
    axes[0].legend(
        loc="lower left",
        frameon=False,
        fontsize=8,
    )
    fig.tight_layout()
    fig.savefig(FIGURES / "event_windows.pdf")
    fig.savefig(FIGURES / "event_windows.png", dpi=200)
    plt.close(fig)


def main() -> None:
    summary = json.loads((DERIVED / "summary.json").read_text())
    daily = pl.read_parquet(DERIVED / "daily_summary.parquet")
    assert daily["posts"].sum() == summary["total_posts"]
    assert date.fromisoformat(summary["last_date"]) >= ANALYSIS_END
    PAPER.mkdir(exist_ok=True)
    FIGURES.mkdir(exist_ok=True)
    build_variables(summary, daily)
    build_figures(daily)
    build_event_figure(summary)
    print("Generated variables and three figures through", ANALYSIS_END)


if __name__ == "__main__":
    main()
